### ISSUE TITLE
ChestESP is not highlighting containers anymore.

### ISSUE THREAD

**Issue by etiennebs** [Wurst-Imperium/ChestESP#6]
So like 3 days ago, when I installed it, everything worked fine. I had  **Cloth Config** and **Mod Menu** installed.
But then somehow nothing got highlighted anymore. 
These is **nothing** highlighted anymore.
**HOW do I fix that?**
![2024-11-05_19 20 12](https://github.com/user-attachments/assets/6b0a56ff-aef8-45b4-a188-fa2ca1f04f52)

**Comment by Alexander01998** [comment]
Hey @etiennebs,

The most likely cause for this behavior would be that ChestESP is disabled in the settings, so as a first troubleshooting step, let's make sure that's not the case.

Find ChestESP in ModMenu, click on the "Configure" button, and make sure that the first entry in the list says "Yes" in green text.

![how to find ChestESP configure button in ModMenu](https://github.com/user-attachments/assets/b37d479b-b057-4257-89d9-2bddc8599d7f)

![ChestESP enable/disable setting](https://github.com/user-attachments/assets/e539b6b3-f5f0-4d72-86bb-01c0e647d44b)

If ChestESP is enabled but still not highlighting anything, my next guess would be a conflict with another mod, shader, or resource pack that might be turning the ESP invisible.

To troubleshoot this, try uninstalling all other mods, shaders, and resource packs so that only ChestESP, ModMenu, Cloth Config, and Fabric API are left. If the chests are now being highlighted correctly, this would suggest that there is indeed a conflict.

If this is the case, try adding your other mods back one at a time until you find the one that is causing the highlights to disappear. Then hold down F3+C for ten seconds to generate a crash report file and post that file here. I will investigate what's causing the incompatibility and see if I can fix it.

Should you find that ChestESP still doesn't work for you, even when you've made sure it's enabled and you've removed all other mods, resource packs, shaders, and so on, please also generate a crash report file and post it here, because in that case, the diagnostic data from a crash report file might still give us some clues as to what could be causing the issue.

**Comment by etiennebs** [comment]
hi man, thanks for the advice! actually, i found the fix. i disabled every resource pack and then one by one activated them to see which one is causing the issues. and guess what? after i disabled everything, it worked again, and after having every resourcepack
activated again it was **Still** working. So it didnt work with one pack, but now works again with the pack! pretty weird but im happy it works!

**Comment by Alexander01998** [comment]
Good to hear that you got it working again! Marking this as resolved for now. Feel free to reopen if and when you find out what was causing that weird issue.
